### ISSUE TITLE
Container won't start if multiple routes are present

### ISSUE THREAD

**Issue by mnowiasz** [Tecnativa/docker-postfix-relay#2]
Hi,

when multiple routes are present the container won't start:

postconf: fatal: -e, -X, or -# accepts no multi-line input

The problematic line in entrypoint is:

routes=$(ip route | grep -v default | cut -d' ' -f1)

When you have more than one route, routes will be a multi line array:

ip route | grep -v default | cut -d ' ' -f1  
10.0.0.0/24
10.0.1.0/24
172.18.0.0/16

When you change the line to

routes=$(ip route | grep -v default | cut -d' ' -f1 | tr '\n' ' ')

All routes are poperly set in main.cf.

**Comment by yajo** [comment]
Thanks for the report. Do you want to volunteer the PR?

**Comment by mnowiasz** [comment]
Done - since this is my first pull request on github I hope I did everything OK :-)
