### ISSUE TITLE
docker smtp relay to enable scanner to send mail

### ISSUE THREAD

**Issue by pdwonline** [Tecnativa/docker-postfix-relay#4]
Hopefully, you can help me getting the smtp-relay configured right. I have a HP Color LaserJet CM6040 MFP that is able to scan documents and send them to an smtp gateway. Since this machine is somewhat older it does not support TLS. I like to solve this by using a plain (unsafe) smtp relay in my local network an then have that foreward it using my google account with TLS. Somehow, I could not get this working. This is what I have set up:

On my server in the local network I have started the docker image for postfix-relay:

sudo docker --name smtp -d --restart=always -p 25:25 -e MAIL_RELAY_HOST='smtp.gmail.com' -e MAIL_RELAY_PORT='587' -e MAIL_RELAY_USER='myaccount@gmail.com' -e MAIL_RELAY_PASS='supersecretpassword' tecnativa/postfix-relay

My printer points to this local server on port 25 with no SSL and no authentication.
I scan a page and tell the printer to send it to myemail@mydomain.com
The printer recognises the smtp gateway and send its data, but a few seconds later it says something like "could not send data because mail gateway rejected"

Waht am I doing wrong?

**Comment by yajo** [comment]
Can you give me the logs?

**Comment by pdwonline** [comment]
This is a part of the log. I changed my email adress for privacy reasons:

Starting Postfix Mail Transport Agent: postfix.
Dec 10 16:04:04 96c78b48199a entrypoint[9]: Docker entrypoint start
Dec 10 16:04:08 96c78b48199a entrypoint[9]: Docker entrypoint configured
Dec 10 16:00:09 96c78b48199a postfix/master[495]: daemon started -- version 3.1.8, configuration /etc/postfix
Dec 10 16:00:34 96c78b48199a postfix/smtpd[499]: connect from unknown[192.168.8.4]
Dec 10 16:00:34 96c78b48199a postfix/smtpd[499]: disconnect from unknown[192.168.8.4] ehlo=1 quit=1 commands=2
Dec 10 16:01:11 96c78b48199a postfix/smtpd[499]: connect from unknown[192.168.8.4]
Dec 10 16:01:12 96c78b48199a postfix/smtpd[499]: NOQUEUE: reject: RCPT from unknown[192.168.8.4]: 454 4.7.1 <mymail@mydomain.nl>: Relay access denied; from=<mymail@gmail.com> to=<mymail@mydomain.nl> proto=ESMTP helo=<192.168.8.4>
Dec 10 16:01:12 96c78b48199a postfix/smtpd[499]: disconnect from unknown[192.168.8.4] ehlo=1 mail=1 rcpt=0/1 quit=1 commands=3/4
Dec 10 16:01:12 96c78b48199a postfix/smtpd[499]: connect from unknown[192.168.8.4]

**Comment by yajo** [comment]
You are probably missing some config parameter. Set all of these to correct values:

- MAILNAME
- MAIL_RELAY_HOST
- MAIL_RELAY_PORT
- MAIL_RELAY_USER
- MAIL_RELAY_PASS
- MAIL_CANONICAL_DOMAINS
- MAIL_NON_CANONICAL_DEFAULT

Configuring gmail to allow plain SMTP access has some difficulties that you maybe didn't get into account: https://support.google.com/a/answer/176600?hl=en

**Comment by pdwonline** [comment]
I am sorry, but maybe I do not understand this well.
What am I suppost to fill in for MAILNAME ?  Is that the subject of Person name?
And what does MAIL_CANONICAL_DOMAINS mean?  Is that the domain name where I can mail to?

**Comment by pdwonline** [comment]
just tested with smtp over telnet. There i figured out that the smtp gateway replies 'Relay access denied' to any rcpt to command.

is there whitelist that I should configure?

```
Trying <myIp>
Connected to <myIp>
Escape character is '^]'.
220 localhost ESMTP Postfix (Debian/GNU)
helo mymail@gmail.com
250 localhost
mail from: mymail@gmail.com
250 2.1.0 Ok
rcpt to: validemail@somewhere.com
454 4.7.1 <validemail@somewhere.com>: Relay access denied

```

**Comment by yajo** [comment]
More or less follow this example:

```env
MAILNAME=example.com
RELAY_HOST=smtp.example.com
RELAY_PORT=587
RELAY_USER=postmaster@example.com
RELAY_PASS=example password
CANONICAL_DOMAINS=example.com
NON_CANONICAL_DEFAULT=example.com
```

**Comment by yajo** [comment]
Stale.
