### ISSUE TITLE
allow postfix "mynetworks" editing

### ISSUE THREAD

**Issue by andreabolandrina** [Tecnativa/docker-postfix-relay#6]
Hi,

Thanks for the easy postfix installation.

Is there an easy way to extend the "mynetworks" postfix config please?
For example I'd like to allow several local subnets.. or even (10.0.0.0/8).

Regards,
Andrea

**Comment by yajo** [comment]
Not, currently it's autodetected in the entrypoint: https://github.com/Tecnativa/docker-postfix-relay/blob/0d869f935e85b5de08d70fb19996219e6b8de9c6/entrypoint#L33-L37

PRs welcome :wink:, closing for now.

**Comment by andreabolandrina** [comment]
PR submitted
